spring.application.name=PharmacyApp
spring.datasource.url=jdbc:postgresql://localhost:5432/pharmacyapp
spring.datasource.username=postgres
spring.datasource.password=1234

paypal.client.id=AU55oVR5j2zdtFde1YT9arEePPC9e1A3nO4oBZQeNIXyOTN_gF_5CXCP0O9qsSYQhsa7rVW_Owc3S6YS
paypal.client.secret=EBrpHYokYYHrNv5GIjMTvEJ09-Tqi5S2Autxa5eOVcRfnmCOg9mLTXdZeIad_oG3R_77g319L6erqiqL
paypal.base-url=https://api-m.sandbox.paypal.com

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect